// frontend/src/components/PlayerTable.vue
<script setup lang="ts">
import type { ScoredStat } from '../types'
import { compactNumber, percent, score } from '../utils/format'

defineProps<{ items: ScoredStat[] }>()
</script>

<template>
  <div class="table-wrap">
    <table class="table">
      <thead>
        <tr>
          <th>排名</th>
          <th>玩家</th>
          <th>帮会</th>
          <th>职业</th>
          <th>所在团</th>
          <th>击败</th>
          <th>助攻</th>
          <th>KDA</th>
          <th>参团率</th>
          <th>玩家伤害</th>
          <th>建筑伤害</th>
          <th>综合分</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item in items" :key="`${item.guild_name}-${item.player_name}-${item.row_number}`">
          <td><span class="rank">{{ item.guild_rank }}</span></td>
          <td>
            <router-link class="player-link" :to="`/players/latest/${item.row_number}`">{{ item.player_name }}</router-link>
          </td>
          <td>{{ item.guild_name }}</td>
          <td><span class="badge purple">{{ item.career }}</span></td>
          <td>{{ item.team_leader }}</td>
          <td>{{ item.kills }}</td>
          <td>{{ item.assists }}</td>
          <td>{{ score(item.kda_ratio) }}</td>
          <td>{{ percent(item.participation_rate) }}</td>
          <td>{{ compactNumber(item.player_damage) }}</td>
          <td>{{ compactNumber(item.building_damage) }}</td>
          <td><span class="score">{{ score(item.composite_score) }}</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// frontend/src/components/PlayerTable.tsx
import type { PlayerSummary } from "../types";
import { formatNumber, percent } from "../utils";

export function PlayerTable({ players, onOpen }: { players: PlayerSummary[]; onOpen?: (statId: number) => void }) {
  return (
    <div className="table-wrap">
      <table className="table">
        <thead>
          <tr>
            <th>排名</th>
            <th>玩家</th>
            <th>职业</th>
            <th>所在团</th>
            <th>击败</th>
            <th>助攻</th>
            <th>KDA</th>
            <th>玩家伤害</th>
            <th>建筑伤害</th>
            <th>参团率</th>
            <th>综合分</th>
          </tr>
        </thead>
        <tbody>
          {players.map((player, index) => (
            <tr key={player.stat_id} onClick={() => onOpen?.(player.stat_id)} className={onOpen ? "clickable-row" : ""}>
              <td>
                <span className="rank">{player.guild_rank ?? index + 1}</span>
              </td>
              <td className="player-cell">
                <img className="avatar" src={player.avatar_url} alt="" />
                {player.player_name}
              </td>
              <td>
                <span className="badge">{player.career}</span>
              </td>
              <td>{player.team_leader}</td>
              <td>{formatNumber(Number(player.kills))}</td>
              <td>{formatNumber(Number(player.assists))}</td>
              <td>{formatNumber(Number(player.kda_ratio))}</td>
              <td>{formatNumber(Number(player.player_damage || 0))}</td>
              <td>{formatNumber(Number(player.building_damage || 0))}</td>
              <td>{percent(Number(player.participation_rate || 0))}</td>
              <td>
                <span className="score">{formatNumber(Number(player.composite_score))}</span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
